bookers/config/routes.rb
Rails.application.routes.draw do
  get '/search', to: 'searches#search'
  get 'users/show'
  get 'user/show' 
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

root to: "homes#top"
get "home/about", to: "homes#about"
resources :books, only: [:create, :index, :show, :edit, :update, :destroy] do
 resource :favorites, only: [:create, :destroy]
 resources :book_comments, only: [:create, :destroy]
end

resources :users, only: [:show, :index, :edit, :update] do
 member do
     get :follows, :followers
 end
 resource :relationships, only: [:create, :destroy]

end



end

bookers/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

bookers/app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end


 
 validates :title, presence: true
 validates :body, presence: true, length: {maximum: 200} 
 
end

bookers/app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

validates :comment, presence: true

end

bookers/app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book



end

bookers/app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

bookers/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower 
  
  
  attachment :profile_image
  
  validates :name, length: {minimum: 2, maximum: 20}, uniqueness: true
  validates :introduction, length: {maximum: 50} 
  
  def follow(user_id)
    follower.create(followed_id: user_id)
  end
  
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    following_user.include?(user)
  end

  
end

bookers/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(@user.id)
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

end

bookers/app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    @book_comment = BookComment.new
    @book = Book.find(params[:id])
  end

  def destroy
    BookComment.find_by(id: params[:id]).destroy
    @book_comment = BookComment.new
    @book = Book.find(params[:id])

  end


  private
   def book_comment_params
     params.require(:book_comment).permit(:comment)
   end


end

bookers/app/controllers/books_controller.rb
class BooksController < ApplicationController

  def show
    @book = Book.find(params[:id])
    @user = current_user
    @book1 = Book.new
    @book_comment = BookComment.new
    @following_users = @book.user.following_user
    @follower_users = @book.user.follower_user
  end

  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
    @following_users = @user.following_user
    @follower_users = @user.follower_user
  end

  def create
    @book = Book.new(book_params)
    @user = current_user
    @books = Book.all
    @book.user_id = current_user.id
    @following_users = @user.following_user
    @follower_users = @user.follower_user
    if @book.save
    flash[:notice] = "You have created book successfully."
    redirect_to book_path(@book.id)
    else
    render :index
    end
  end

  def edit
    @user = current_user
    @book = Book.find(params[:id])
   if @book.user == current_user
     render "edit"
   else
     redirect_to books_path
   end
  end

  def update
    @user = current_user
    @book = Book.find(params[:id])
    if @book.update(book_params)
     flash[:notice] = "You have updated book successfully."
    redirect_to book_path(@book.id)
    else
    render :edit
    end
  end

  def destroy
    book =Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

bookers/app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
  end
  
  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
  end
  
end

bookers/app/controllers/homes_controller.rb
class HomesController < ApplicationController

 
 def top
  @user = current_user
 end

end

bookers/app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  
def create
 current_user.follow(params[:user_id])
 redirect_to request.referer
end

def destroy
  current_user.unfollow(params[:user_id])
  redirect_to request.referer
end
  
  
end

bookers/app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def search
   @model = params["model"]
   @content = params["content"]
   @method = params["method"]
   @records = search_for(@model, @content, @method)
   @user = current_user
  end

  private
  def search_for(model, content, method)
    if model == 'user'
      if method == 'perfect'
        User.where(name: content)
      elsif method == 'partial'
        User.where('name LIKE ?', '%'+content+'%')
      elsif method == 'forward'
        User.where('name LIKE ?', '%'+content)  
      else
        User.where('name LIKE ?', content+'%')
      end
      
    elsif model == 'book'
      if method == 'perfect'
        Book.where(title: content)
      elsif method == 'partial'
        Book.where('title LIKE ?', '%'+content+'%')
      elsif method == 'forward'
        Book.where('title LIKE ?', '%'+content ) 
      else 
        Book.where('title LIKE ?', content+'%' ) 
      end
    end
  end 
    
end

bookers/app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :correct_user, only: [:edit, :update]

  def show
    @user1 = User.find(params[:id])
    @books = @user1.books
    @user = current_user
    @book =Book.new
    @following_users = @user1.following_user
    @follower_users = @user1.follower_user
  end

  def index
    @users = User.all.order(updated_at: :desc)
    @book = Book.new
    @user = current_user
    @following_users = @user.following_user
    @follower_users = @user.follower_user
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
   @user = User.find(params[:id])
    if @user.update(user_params)
    flash[:notice] = "You have updated user successfully."
    redirect_to user_path(@user.id)
    else
    render :edit
    end
  end

  def follows
   user = User.find(params[:id])
   @user = current_user
   @users = user.following_user
  end

  def followers
   user = User.find(params[:id])
   @user = current_user
   @users = user.follower_user
  end



 private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def correct_user

    user = User.find(params[:id])
    if current_user != user
      redirect_to user_path(current_user.id)
    end
  end


end

bookers/app/helpers/application_helper.rb
module ApplicationHelper
end

bookers/app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

bookers/app/helpers/books_helper.rb
module BooksHelper
end

bookers/app/helpers/favorites_helper.rb
module FavoritesHelper
end

bookers/app/helpers/finders_helper.rb
module FindersHelper
end

bookers/app/helpers/homes_helper.rb
module HomesHelper
end

bookers/app/helpers/relationships_helper.rb
module RelationshipsHelper
end

bookers/app/helpers/searches_helper.rb
module SearchesHelper
end

bookers/app/helpers/users_helper.rb
module UsersHelper
end

bookers/app/views/book_comments/_comment.html.erb
<% book.book_comments.each do |book_comment| %>
 <tr>
  <td><%= attachment_image_tag book.user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "50x50" %><br>
   <%= link_to book_comment.user.name, user_path(book.user.id) %></td>
  <td><%= book_comment.comment %></td>
   <% if book_comment.user == current_user%>
    <td><%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, remote: true %></td>
   <% end %>
 </tr>
<% end %>
<tr>
 <td>
  <%= form_with(model:[book, book_comment], remote: true) do |f|%>
   <%= f.text_area :comment, row:"5" %>
   <%= f.submit "送信" %>
  <% end %>
 </td>
</tr>

bookers/app/views/books/_list.html.erb
<div class="col-md-3">
 <h2>User info</h2>
 <div><%= attachment_image_tag user1, :profile_image, :fill, 100,100, format: "jpeg", fallback:"no_image.jpeg" %></div>
  <table class="table">
   <tbody>
    <tr></tr>
    <tr>
     <th>name</th>
     <th><%= user1.name %></th>
    </tr>
    
    <tr>
     <th>introduction</th>
     <th><%= user1.introduction %></th>
    </tr>

    <tr>
     <th>follow</th>
     <th>
     <%= link_to follows_user_path(user1) do %>
     <%= following_users.count %>
     <% end %>
     </th>
    </tr>

    <tr>
     <th>follower</th>
     <th>
     <%= link_to followers_user_path(user1) do %>
     <%= follower_users.count %>
     <% end %>
     </th>
    </tr>
    
    <tr>
     <th>
     <%= link_to "", edit_user_path(user1), class:"btn btn-outline-secondary btn-block fas fa-user-cog" %>
     </th>
    </tr>
    
    <tr>
     <% if current_user != user1 %>
     <th>
     <% if current_user.following?(user1) %>
     <%= link_to 'フォロー外す', user_relationships_path(user1.id), method: :delete, class: "btn-sm btn-danger" %>
     <% else %>
     <%= link_to 'フォローする', user_relationships_path(user1.id), method: :POST, class:"btn-sm btn-success" %>
     <% end %>
     </th>
     <% end %>
    </tr>
    
   </tbody>
  </table>


<h2 class="mt-3">New book</h2>
<%= form_with model: book, local:true do |f| %>
  <div class="form-group">
   <label for="book_title">Title</label>
   <div><%= f.text_field :title %></div>
  </div>
  <div class="form-group">
   <label for="book_opinion">Opinion</label>
   <div><%= f.text_field :body %></div>
  </div>

  <div class="form-group">
   <%= f.submit "Create Book", class:"btn btn-success" %>
  </div>
<% end %>
</div>

bookers/app/views/books/edit.html.erb
<% if @book.errors.any? %>
 <div id="error_explanation">
  <%= @book.errors.count %> errors prohibited this obj from being saved:
  <% @book.errors.full_messages.each do |message| %>
   <ul>
    <li>
    <%= message %>
    </li>
   </ul>
  <% end %>
 </div>
<% end %>

<div class="container">
 <div class="row">
  <div class="col-sm-12 col-md-8 col-lg-5 px-sm-0 mx-auto">
   <h1>Editing Book</h1>
   <%= form_with model: @book, local:true do |f| %>
   <div class="form-group">
    <label for="book_title">Title</label>
    <div><%= f.text_field :title %></div>
   </div>
   <div class="form-group">
    <label for="book_opinion">Opinion</label>
    <div><%= f.text_field :body %></div>
   </div>
   <div class="form-group">
   <div><%= f.submit "Update Book", class:"btn btn-success" %></div>
   </div>
   <% end %>

   <%= link_to "Show", book_path(@book.id) %>
   |
   <%= link_to "Back", books_path %>
  </div>
 </div>
</div>

bookers/app/views/books/index.html.erb
<main>
 <% if @book.errors.any? %>
  <div id="error_explanation">
  <%= @book.errors.count %> errors prohibited this obj from being saved:
  <% @book.errors.full_messages.each do |message| %>
  <ul>
    <li>
    <%= message %>
    </li>
  </ul>
  <% end %>
  </div>
<% end %>
 <div class="container px-5 px-sm-0">
  <div class="row">
   <%= render "books/list", book: @book, user1: @user, following_users:  @following_users, follower_users: @follower_users %>
   <div class="col-md-8 offset-md-1">
    <h2>Books</h2>
    <table class="table table-hover table-inverse">
     <thead>
      <tr>
       <th></th>
       <th>Title</th>
       <th>Opinion</th>
       <th colspan="3"></th>
      </tr>
     </thead>
     <tbody>
     <% @books.each do |book| %>
      <tr>
       <td>
       <%= link_to user_path(book.user.id) do %>
       <%= attachment_image_tag book.user, :profile_image, :fill, 90,90, fallback:"no_image.jpg" %>
       <% end %>
       </td>
       <td><%= link_to book.title, book_path(book.id) %></td>
       <td id="favorite_buttons"><%= render "favorites/favorites", book: book %></td>
       <td>
        <%= link_to"コメント数:#{book.book_comments.count}", book_path(book.id) %>
       </td>
      </tr>
     </tbody>
     <% end %>
     </table>
   </div>
  </div>
 </div>
</main>

bookers/app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
 <div class="row">

  <% if @book_comment.errors.any? %>
<div id="error_explanation">
  <%= @book_comment.errors.count %> errors prohibited this obj from being saved:
  <% @book_comment.errors.full_messages.each do |message| %>
   <ul>
     <li>
    <%= message %>
     </li>
   </ul>
  <% end %>
</div>
<% end %>



  <%= render "books/list", book: @book1, user1: @book.user, following_users: @following_users, follower_users: @follower_users %>

  <div class="col-md-8 offset-md-1">
   <h2>Book detail</h2>
   <table class="table">
    <tbody>
     <tr>
       <td><%= attachment_image_tag @book.user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "100x100" %><br/>
       <%= link_to @book.user.name, user_path(@book.user.id) %></td>
       <td><%= link_to @book.title, book_path(@book.id) %></td>
       <td><%= @book.body %></td>
       <td id="favorite_buttons_<%= @book.id %>"><%= render "favorites/favorites", book: @book %></td>
       <td>
        <p>コメント数:<%=@book.book_comments.count %></p>
       </td>
       <% if @book.user == current_user %>
       <td><%= link_to"Edit", edit_book_path(@book.id), class:"btn btn-sm btn-success" %></td>
       <td><%= link_to"Destroy", book_path(@book.id), method: :delete,data: {confirm: "Are you sure？"}, class:"btn btn-sm btn-danger destroy" %></td>
       <td></td>
       <% end %>
     </tr>
       <div id="comments-area"><%= render "book_comments/comment", book: @book, book_comment: @book_comment %></div>
   </tbody>
  </table>
 </div>
  </div>
 </div>

bookers/app/views/favorites/_favorites.html.erb
<td>
 <% if book.favorited_by?(current_user) %>
  <p>
   <%= link_to book_favorites_path(book.id), method: :delete, remote: true do %>
    <i class="far fa-heart unlike-btn"><%= book.favorites.count %></i>
   <% end %>
  </p>
 <% else %>
  <p>
  <%= link_to book_favorites_path(book.id), method: :post, remote: true do %>
   <i class="far fa-heart like-btn"><%= book.favorites.count %></i>
  <% end %>
  </p>
 <% end %>
</td>

bookers/app/views/favorites/create.js.erb
$("#favorite_buttons_<%= @book.id %>").html("<%= j(render 'favorites/favorites', book: @book}) %>");

bookers/app/views/favorites/destroy.js.erb
$('#favorite_buttons_<%= @book.id %>').html("<%= j(render "favorites/favorites", book: @book) %>");

bookers/app/views/users/edit.html.erb
<% if @user.errors.any? %>
<div id="error_explanation">
  <%= @user.errors.count %> errors prohibited this obj from being saved:
  <% @user.errors.full_messages.each do |message| %>
   <ul>
     <li>
    <%= message %>
     </li>
   </ul>
  <% end %>
</div>
<% end %>

<div class="container">
 <div class="row">
   <div class="col-sm-12 col-md-8 collg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f|%>
    <div class="form-group">
      <label for="user_name">Name</label>
      <div><%= f.text_field :name, autofocus: true, id:"inputName" %></div>
    </div>
    <div class="form-group">
      <label for="user_image">Image</label>
      <div><%= f.attachment_field :profile_image %></div>
    </div>
    <div class ="form-group">
      <label for"user_introduction">Introduction</label>
      <div><%= f.text_field :introduction, autofocus: true, id:"inputIntroduction" %></div>
    </div>
    <div class="form-group">
      <div><%= f.submit "Update User", class:"btn btn-secondary" %></div>
    <% end %>
    </div>
   </div>
 </div>
</div>

bookers/app/views/users/followers.html.erb
 <h2>Follower Users</h2>
  <table class="table">
   <thead>
    <tr>
     <th>image</th>
     <th>name</th>
     <th colspan="3"></th>
    </tr>
   </thead>
   <tbody>
    <% @users.each do |user| %>
    <tr>
     <td><%= attachment_image_tag user, :profile_image, :fill, 90,90, fallback:"no_image.jpg"%></td>
     <td><%= user.name %></td>
     <td>フォロー数：<%= user.following_user.count %></td>
     <td>フォロワー数：<%= user.follower_user.count %></td>
   
     <td><%= link_to "Show", user_path(user.id) %></td>
    </tr>
   </tbody>
    <% end %>
  </table>

bookers/app/views/users/follows.html.erb
 <h2>Follow Users</h2>
  <table class="table">
   <thead>
    <tr>
     <th>image</th>
     <th>name</th>
     <th colspan="3"></th>
    </tr>
   </thead>
   <tbody>
    <% @users.each do |user| %>
    <tr>
     <td><%= attachment_image_tag user, :profile_image, :fill, 90,90, fallback:"no_image.jpg"%></td>
     <td><%= user.name %></td>
     <td>フォロー数：<%= user.following_user.count %></td>
     <td>フォロワー数：<%= user.follower_user.count %></td>
     <td><%= link_to "Show", user_path(user.id) %></td>
    </tr>
   </tbody>
    <% end %>
  </table>

bookers/app/views/users/index.html.erb
<%= render 'searches/form' %>
<div class="container px-5 px-sm-0">
 <div class="row">
 <%= render "books/list", book: @book, user1: @user, following_users:  @following_users, follower_users: @follower_users %>
 <div class="col-md-8 offset-md-1">
  <h2>Users</h2>
  <table class="table">
   <thead>
    <tr>
     <th>image</th>
     <th>name</th>
     <th colspan="3"></th>
    </tr>
   </thead>
   <tbody>
    <% @users.each do |user| %>
    <tr>
     <td><%= attachment_image_tag user, :profile_image, :fill, 90,90, fallback:"no_image.jpg"%></td>
     <td><%= user.name %></td>
     <td>フォロー数：<%= user.following_user.count %></td>
     <td>フォロワー数：<%= user.follower_user.count %></td>

     <% if user == current_user %>
     <th>me</th>
     <% end %>
     <% if current_user != user %>
     <th>
      <% if current_user.following?(user) %>
      <%= link_to 'フォロー外す', user_relationships_path(user.id), method: :delete, class: "btn-sm btn-danger" %>
      <% else %>
      <%= link_to 'フォローする', user_relationships_path(user.id), method: :POST, class:"btn-sm btn-success" %>
      <% end %>
     </th>
     <% end %>

     <td><%= link_to "Show", user_path(user.id) %></td>
    </tr>
   </tbody>
   <% end %>
  </table>
 </div>
 </div>
</div>

bookers/app/views/users/show.html.erb
<main>
<div class="container px-5 px-sm-0">
 <div class="row">

  <%= render "books/list", book: @book, user1: @user1, following_users: @following_users, follower_users: @follower_users %>
  <div class="col-md-8 offset-md-1">
   <h2>Books</h2>
   <table class="table table-hover table-inverse">
    <thead>
     <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
     </tr>
    </thead>
    <tbody>
    <% @books.each do |book| %>
     <tr>
      <td>
       <%= link_to user_path(@user1.id) do %>
       <%= attachment_image_tag @user1, :profile_image, :fill, 100,100, format: "jpeg", fallback:"no_image.jpeg" %>
       <% end %>
      </td>
      <td><%= link_to book.title, book_path(book.id) %></td>
      <td><%= book.body %></td>
      <td>
        <%= link_to"コメント数:#{book.book_comments.count}", book_path(book.id) %>
       </td>
     </tr>
    <% end %>
    </tbody>
   </table>
  </div>
 </div>
 </main>