bookers/config/routes.rb
Rails.application.routes.draw do
  get '/search', to: 'searches#search'
  get 'users/show'
  get 'user/show' 
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

root to: "homes#top"
get "home/about", to: "homes#about"
resources :books, only: [:create, :index, :show, :edit, :update, :destroy] do
 resource :favorites, only: [:create, :destroy]
 resources :book_comments, only: [:create, :destroy]
end

resources :users, only: [:show, :index, :edit, :update] do
 member do
     get :follows, :followers
 end
 resource :relationships, only: [:create, :destroy]

end



end

bookers/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

bookers/app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end


 
 validates :title, presence: true
 validates :body, presence: true, length: {maximum: 200} 
 
end

bookers/app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

validates :comment, presence: true

end

bookers/app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book



end

bookers/app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

bookers/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower 
  
  
  attachment :profile_image
  
  validates :name, length: {minimum: 2, maximum: 20}, uniqueness: true
  validates :introduction, length: {maximum: 50} 
  
  def follow(user_id)
    follower.create(followed_id: user_id)
  end
  
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    following_user.include?(user)
  end

  
end

bookers/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(@user.id)
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

end

bookers/app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    @book_comment = BookComment.new
    @book = Book.find(params[:id])
  end

  def destroy
    BookComment.find_by(id: params[:id]).destroy
    @book_comment = BookComment.new
    @book = Book.find(params[:id])

  end


  private
   def book_comment_params
     params.require(:book_comment).permit(:comment)
   end


end

bookers/app/controllers/books_controller.rb
class BooksController < ApplicationController

  def show
    @book = Book.find(params[:id])
    @user = current_user
    @book1 = Book.new
    @book_comment = BookComment.new
    @following_users = @book.user.following_user
    @follower_users = @book.user.follower_user
  end

  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
    @following_users = @user.following_user
    @follower_users = @user.follower_user
  end

  def create
    @book = Book.new(book_params)
    @user = current_user
    @books = Book.all
    @book.user_id = current_user.id
    @following_users = @user.following_user
    @follower_users = @user.follower_user
    if @book.save
    flash[:notice] = "You have created book successfully."
    redirect_to book_path(@book.id)
    else
    render :index
    end
  end

  def edit
    @user = current_user
    @book = Book.find(params[:id])
   if @book.user == current_user
     render "edit"
   else
     redirect_to books_path
   end
  end

  def update
    @user = current_user
    @book = Book.find(params[:id])
    if @book.update(book_params)
     flash[:notice] = "You have updated book successfully."
    redirect_to book_path(@book.id)
    else
    render :edit
    end
  end

  def destroy
    book =Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

bookers/app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
  end
  
  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
  end
  
end

bookers/app/controllers/homes_controller.rb
class HomesController < ApplicationController

 
 def top
  @user = current_user
 end

end

bookers/app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def search
   @model = params["model"]
   @content = params["content"]
   @method = params["method"]
   @records = search_for(@model, @content, @method)
   @user = current_user
  end

  private
  def search_for(model, content, method)
    if model == 'user'
      if method == 'perfect'
        User.where(name: content)
      elsif method == 'partial'
        User.where('name LIKE ?', '%'+content+'%')
      elsif method == 'forward'
        User.where('name LIKE ?', '%'+content)  
      else
        User.where('name LIKE ?', content+'%')
      end
      
    elsif model == 'book'
      if method == 'perfect'
        Book.where(title: content)
      elsif method == 'partial'
        Book.where('title LIKE ?', '%'+content+'%')
      elsif method == 'forward'
        Book.where('title LIKE ?', '%'+content ) 
      else 
        Book.where('title LIKE ?', content+'%' ) 
      end
    end
  end 
    
end

bookers/app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :correct_user, only: [:edit, :update]

  def show
    @user1 = User.find(params[:id])
    @books = @user1.books
    @user = current_user
    @book =Book.new
    @following_users = @user1.following_user
    @follower_users = @user1.follower_user
  end

  def index
    @users = User.all.order(updated_at: :desc)
    @book = Book.new
    @user = current_user
    @following_users = @user.following_user
    @follower_users = @user.follower_user
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
   @user = User.find(params[:id])
    if @user.update(user_params)
    flash[:notice] = "You have updated user successfully."
    redirect_to user_path(@user.id)
    else
    render :edit
    end
  end

  def follows
   user = User.find(params[:id])
   @user = current_user
   @users = user.following_user
  end

  def followers
   user = User.find(params[:id])
   @user = current_user
   @users = user.follower_user
  end



 private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def correct_user

    user = User.find(params[:id])
    if current_user != user
      redirect_to user_path(current_user.id)
    end
  end


end

bookers/app/helpers/application_helper.rb
module ApplicationHelper
end

bookers/app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

bookers/app/helpers/books_helper.rb
module BooksHelper
end

bookers/app/helpers/favorites_helper.rb
module FavoritesHelper
end

bookers/app/helpers/finders_helper.rb
module FindersHelper
end

bookers/app/helpers/homes_helper.rb
module HomesHelper
end

bookers/app/helpers/relationships_helper.rb
module RelationshipsHelper
end

bookers/app/helpers/searches_helper.rb
module SearchesHelper
end

bookers/app/helpers/users_helper.rb
module UsersHelper
end

bookers/app/views/homes/about.html.erb
<div class="container">
 <div class="row">
   <h1 class="px-3 mx-auto">
     Welcome 
     <i class="fas fa-book"></i>
     <strong>Bookers</strong>
    !
   </h1>
 </div>
</div>

bookers/app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>Welcome to
      <i class="fas fa-book"></i>
      <strong>Bookers</strong>
      !!
      </h1>
      <p>In <i class="fas fa-book"></i><strong>Bookers</strong>,</p> 
      <p>you can share and exchange your opinions , inpressions , and emotions</p>
      <p>about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to "Log in", new_user_session_path, class:"btn btn-info btn-sm btn-block mb-3" %>
        </div>
        <div class="row">
          <%= link_to "Sign up", new_user_registration_path, class:"btn btn-success btn-sm btn-block" %>
        </div>
      </div>
    </div>
  </div>
</div>

bookers/app/views/searches/_form.html.erb
<% if user_signed_in? %>
    <%= form_tag(search_path, method: :get) do %>
      <%= text_field_tag 'content' %>
      <%= select_tag 'model', options_for_select({ "User" => "user", "Book" => "book" }) %>
      <%= select_tag 'method', options_for_select({ "完全一致" => "perfect", "部分一致" => "partial", "前方一致" => "forward", "後方一致" => "backward"}) %>
      <%= submit_tag '検索' %>
    <% end %>
<% end %>

bookers/app/views/searches/search.html.erb
<%= render 'searches/form' %>
<% if @model == 'user' %>
  <h3>Users searches for "<%= @content %>"</h3>
     <% @records.each do |user| %>
      <%= link_to user_path(user) do %>
      <%= user.name %><br>
      <% end %>
     <% end %>
   </tbody>
  <% else @model == 'books' %>
  <h3>Books searches for "<%= @content %>"</h3>
   <table class="table table-hover table-inverse">
     <thead>
      <tr>
       <th></th>
       <th>Title</th>
       <th>Opinion</th>
       <th colspan="3"></th>
      </tr>
     </thead>
     <tbody>
     <% @records.each do |book| %>
      <tr>
       <td>
       <%= link_to user_path(book.user.id) do %>
       <%= attachment_image_tag book.user, :profile_image, :fill, 90,90, fallback:"no_image.jpg" %>
       <% end %>
       </td>
       <td><%= link_to book.title, book_path(book.id) %></td>
       <td><%= book.body %></td>
       <td>
       <% if book.favorited_by?(current_user) %>
        <p>
         <%= link_to book_favorites_path(book), method: :delete do %>
         <i class="far fa-heart unlike-btn"></i>
         <%= book.favorites.count %>
         <% end %>
        </p>
        <% else %>
        <p>
          <%= link_to book_favorites_path(book), method: :post do %>
          <i class="far fa-heart like-btn"></i>
          <%= book.favorites.count %>
          <% end %>
        </p>
       <% end %>
       </td>
       <td>
        <%= link_to"コメント数:#{book.book_comments.count}", book_path(book.id) %>
       </td>
      </tr>
     </tbody>
     <% end %>
     </table>
<% end %>