bookers/config/routes.rb
Rails.application.routes.draw do
  get '/search', to: 'searches#search'
  get 'users/show'
  get 'user/show' 
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

root to: "homes#top"
get "home/about", to: "homes#about"
resources :books, only: [:create, :index, :show, :edit, :update, :destroy] do
 resource :favorites, only: [:create, :destroy]
 resources :book_comments, only: [:create, :destroy]
end

resources :users, only: [:show, :index, :edit, :update] do
 member do
     get :follows, :followers
 end
 resource :relationships, only: [:create, :destroy]

end



end

bookers/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

bookers/app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end


 
 validates :title, presence: true
 validates :body, presence: true, length: {maximum: 200} 
 
end

bookers/app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

validates :comment, presence: true

end

bookers/app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book



end

bookers/app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

bookers/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower 
  
  
  attachment :profile_image
  
  validates :name, length: {minimum: 2, maximum: 20}, uniqueness: true
  validates :introduction, length: {maximum: 50} 
  
  def follow(user_id)
    follower.create(followed_id: user_id)
  end
  
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    following_user.include?(user)
  end

  
end

bookers/app/controllers/books_controller.rb
class BooksController < ApplicationController

  def show
    @book = Book.find(params[:id])
    @user = current_user
    @book1 = Book.new
    @book_comment = BookComment.new
    @following_users = @book.user.following_user
    @follower_users = @book.user.follower_user
  end

  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
    @following_users = @user.following_user
    @follower_users = @user.follower_user
  end

  def create
    @book = Book.new(book_params)
    @user = current_user
    @books = Book.all
    @book.user_id = current_user.id
    @following_users = @user.following_user
    @follower_users = @user.follower_user
    if @book.save
    flash[:notice] = "You have created book successfully."
    redirect_to book_path(@book.id)
    else
    render :index
    end
  end

  def edit
    @user = current_user
    @book = Book.find(params[:id])
   if @book.user == current_user
     render "edit"
   else
     redirect_to books_path
   end
  end

  def update
    @user = current_user
    @book = Book.find(params[:id])
    if @book.update(book_params)
     flash[:notice] = "You have updated book successfully."
    redirect_to book_path(@book.id)
    else
    render :edit
    end
  end

  def destroy
    book =Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

bookers/app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
  end
  
  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
  end
  
end

bookers/app/controllers/homes_controller.rb
class HomesController < ApplicationController

 
 def top
  @user = current_user
 end

end

bookers/app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def search
   @model = params["model"]
   @content = params["content"]
   @method = params["method"]
   @records = search_for(@model, @content, @method)
   @user = current_user
  end

  private
  def search_for(model, content, method)
    if model == 'user'
      if method == 'perfect'
        User.where(name: content)
      elsif method == 'partial'
        User.where('name LIKE ?', '%'+content+'%')
      elsif method == 'forward'
        User.where('name LIKE ?', '%'+content)  
      else
        User.where('name LIKE ?', content+'%')
      end
      
    elsif model == 'book'
      if method == 'perfect'
        Book.where(title: content)
      elsif method == 'partial'
        Book.where('title LIKE ?', '%'+content+'%')
      elsif method == 'forward'
        Book.where('title LIKE ?', '%'+content ) 
      else 
        Book.where('title LIKE ?', content+'%' ) 
      end
    end
  end 
    
end

bookers/app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :correct_user, only: [:edit, :update]

  def show
    @user1 = User.find(params[:id])
    @books = @user1.books
    @user = current_user
    @book =Book.new
    @following_users = @user1.following_user
    @follower_users = @user1.follower_user
  end

  def index
    @users = User.all.order(updated_at: :desc)
    @book = Book.new
    @user = current_user
    @following_users = @user.following_user
    @follower_users = @user.follower_user
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
   @user = User.find(params[:id])
    if @user.update(user_params)
    flash[:notice] = "You have updated user successfully."
    redirect_to user_path(@user.id)
    else
    render :edit
    end
  end

  def follows
   user = User.find(params[:id])
   @user = current_user
   @users = user.following_user
  end

  def followers
   user = User.find(params[:id])
   @user = current_user
   @users = user.follower_user
  end



 private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def correct_user

    user = User.find(params[:id])
    if current_user != user
      redirect_to user_path(current_user.id)
    end
  end


end

bookers/app/helpers/application_helper.rb
module ApplicationHelper
end

bookers/app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

bookers/app/helpers/books_helper.rb
module BooksHelper
end

bookers/app/helpers/favorites_helper.rb
module FavoritesHelper
end

bookers/app/helpers/finders_helper.rb
module FindersHelper
end

bookers/app/helpers/homes_helper.rb
module HomesHelper
end

bookers/app/helpers/relationships_helper.rb
module RelationshipsHelper
end

bookers/app/helpers/searches_helper.rb
module SearchesHelper
end

bookers/app/helpers/users_helper.rb
module UsersHelper
end

bookers/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  </head>
  <body>
    <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
     <div class="container">
      <a class="navbar-brand" href="/" >
      <span>Bookers</span>
      </a> 
       <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation"> 
        <span class="navbar-toggler-icon"></span>
       </button>
      <div class="navbar-collapse collapse" id="navbarNavDropdown"> 
        <% if user_signed_in? %>    
        <ul class="navbar-nav ml-auto">
        <li class="nav-item"><%= link_to "Home", user_path(@user.id), class:"fas fa-home nav-link text-light" %></li>
    
        <li class="nav-item"><%= link_to "Users", users_path, class:"fas fa-users nav-link text-light" %></li> 
    
        <li class="nav-item"><%= link_to "Books", books_path,class:"fas fa-book-open nav-link text-light" %></li>
       
        <li class="nav-item"><%= link_to "Log out", destroy_user_session_path, method: :delete, class:"fas fa-sign-out-alt nav-link text-light"%></li>
        </ul>
        <% else %>
       <ul class="navbar-nav ml-auto">
        <li><%= link_to "Home", root_path, class:"fas fa-home nav-link text-light" %></li>
      
         <li><%= link_to "About", home_about_path, class:"fas fa-link nav-link text-light" %></li>
      
         <li><%= link_to "Sign up", new_user_registration_path, class:"fas fa-user-plus nav-link text-light" %></li>
      
         <li><%= link_to "Log in", new_user_session_path, class:"fas fa-sign-in-alt nav-link text-light" %></li>
        </ul>
        <% end %>
       </div>
      </div>
     </nav>
    
    </header> 
    <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "#{key}") %>
   <% end %>
  <%= yield %> 
  <footer>
    <div class="container mt-5">
      <div class="row">
        <div class="mx-auto">
          <p>CopyRight Infratop.inc</p>
        </div>
      </div>
    </div>
  </footer>  
 </body>
</html>